apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowboard-frontend
  labels:
    app: flowboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowboard-frontend
  template:
    metadata:
      labels:
        app: flowboard-frontend
    spec:
      containers:
        - name: flowboard-frontend
          image: flowboard-frontend:local
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://flowboard-backend:8080"
