apiVersion: v1
kind: Service
metadata:
  name: flowboard-frontend
  namespace: flowboard
spec:
  selector:
    app: flowboard-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80